apiVersion: v1
kind: Service
metadata:
    name: bimageforkubernetesmarch31aks1
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: bimageforkubernetesmarch31aks1